routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('bases', basesController::class);

Route::resource('pilots', pilotsController::class);

Route::resource('planes', planesController::class);

Route::resource('members', membersController::class);

Route::resource('flights', flightsController::class);

Route::post('pilots/{basePilotos}', ['as' => 'pilots.store', 'uses' => 'pilotsController@store']);

//Route::put('pilots/{basePilotos}', ['as' => 'pilots.update', 'uses' => 'pilotsController@update']);

Route::post('planes/{basePlanes}', ['as' => 'planes.store', 'uses' => 'planesController@store']);

Route::post('members/{baseMembers}', ['as' => 'members.store', 'uses' => 'membersController@store']);

app/Http/Controllers/basesController.php
<?php

namespace App\Http\Controllers;
use App\Models\bases;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class basesController extends Controller
{
    /** 
     * Muestra la vista con el listado de las bases de datos
     * 
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bases = bases::all();
        return view('bases.index',compact('bases'));
    }

    /**
     * Muestra la vista con el formulario para crear un base aerea
     * 
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('bases.create');
    }

    /**
     * almacena las bases aereas en la base de datos
     * 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $bases = new bases();

        $bases -> name = $request -> input('name');
        $bases -> save();

        return redirect() -> action([basesController::class , 'index'])-> with('status1','La base fue creada correctamente');
    }

    /**
     * Muestra la informacion relacionada a cada base aerea
     * 
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $bases = bases::find($id);
        $bases -> pilots;
        $bases -> planes;
        $bases -> members;

        return view('bases.show',compact('bases'));
    }

    /**
     * muestra la vista para editar la informacion de la base aerea
     * 
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bases = bases::find($id);
        return view('bases.edit',compact('bases'));
    }

    /**
     * Realiza el proceso de actualizaciomn de datos de las bases aereas
     * 
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $bases = bases::findOrFail($id);

        $bases -> name = $request -> input('name');
        $bases -> save();

        return redirect() -> route('bases.index')-> with('status2','La base fue actualizada correctamente');
    }

    /**
     * Elimina los datos de la base aerea junto a esta
     * 
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $bases = bases::find($id);
        $bases -> pilots() -> delete();
        $bases -> planes() -> delete();
        $bases -> members() -> delete();
        $bases -> delete();

        return redirect() -> route('bases.index')-> with('status3','La base fue eliminada correctamente');
    }
}

resources/views/bases/create.blade.php
@extends('bootstrap.layout')

@section('title', 'Bases Aereas')

@section('content')


    <form class="form-group" method="POST" action="{{route('bases.store')}}" enctype="multipart/form-data">
        @csrf
        <div style="padding: 30px; margin-right:50%; ">
            <label class="col-form-label col-form-label-lg" style="margin-bottom: 10px;">
                <H1>Nombre de la base</H1>
            </label>
            <div class="row">
                <label class="col-sm-4">Nombre</label>
                <div class="col">
                    <input type="text" name="name" class="form-control">
                    <small class="form-text text-muted">Nombre de la base aerea.</small>
                </div>
            </div>
            <button type="submit" class="btn btn-primary" style="margin-left: 86%; margin-top:40px">Registrar</button>
        </div>
    </form>

@endsection

resources/views/bases/edit.blade.php
@extends('bootstrap.layout')

@section('title', 'Bases Aereas')

@section('content')


    <form class="form-group" method="POST" action="/bases/{{$bases -> id}}" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div style="padding: 30px; margin-right:50%; ">
            <label class="col-form-label col-form-label-lg" style="margin-bottom: 10px;">
                <H1>Nombre de la base</H1>
            </label>
            <div class="row">
                <label class="col-sm-4">Nombre</label>
                <div class="col">
                    <input type="text" name="name" class="form-control" placeholder="{{$bases -> name}}">
                    <small class="form-text text-muted">Nuevo Nombre de la base.</small>
                </div>
            </div>
            <button type="submit" class="btn btn-primary" style="margin-left: 86%; margin-top:40px">Actualizar</button>
        </div>
    </form>

@endsection

resources/views/bases/index.blade.php
@extends('bootstrap.layout')

@section('title', 'Bases Aereas')

@section('content')

    <div style="margin-left:10%; width:300px;">
        @include('messages.tareas')
    </div>
    <div style="margin_right:30px; margin-top:10px; margin-left: 35%">

        <label style="color: royalblue">
            <h1 style="margin-left: 40px">Lista de bases Aereas</h1>
            <br>

        </label>
        <table class="table" style="width: 500px">
            <thead class="head-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" >Nombres</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($bases as $base)
                    <tr>
                        <th scope="row">{{ $base->id }}</th>
                        <td>{{ $base->name }}</td>
                        <td><a href="http://127.0.0.1:8000/pilots/create?basePilotos={{ $base->id }}"
                                class="btn btn-primary" style="border: none; background: white;"><img
                                    src="/images/piloto.png" style="background: white; height: 20px; width: 20px;"
                                    title="Agregar Piloto"></a>

                            <a href="http://127.0.0.1:8000/planes/create?basePlanes={{ $base->id }}"
                                class="btn btn-primary" style="border: none; background: white;"><img
                                    src="/images/avion.png" style="background: white; height: 20px; width: 20px;"
                                    title="Agregar Avion"></a>

                            <a href="http://127.0.0.1:8000/members/create?baseMembers={{ $base->id }}"
                                class="btn btn-primary" style="border: none; background: white;"><img
                                    src="/images/personal.png" style="background: white; height: 20px; width: 20px;"
                                    title="Agregar Mienbros de la tripulacion"></a>

                            <a href="bases/{{ $base->id }}" class="btn btn-primary"
                                style="border: none; background: white;"><img src="/images/aerolinea.png"
                                    style="background: white; height: 20px; width: 20px;"
                                    title="Ver todo sobre la base"></a>

                            <a href="http://127.0.0.1:8000/bases/{{ $base->id }}/edit" class="btn btn-primary"
                                style="border: none; background: white;"><img src="/images/curriculum.png"
                                    style="background: white; height: 20px; width: 20px;" title="Editar"></a>

                            <form action="{{ route('bases.destroy', $base->id) }}" method="POST" class="form form-group">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-primary" style="border: none; background: white;"><img
                                        src="/images/borrar.png" style="background: white; height: 20px; width: 20px;"
                                        onClick="return confirm('seguro de elinar esta base aerea?')"
                                        title="Eliminar"></button>
                            </form>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
        <div class="row" style="margin-left: 6%">
            <div class="col">
                <a href="http://127.0.0.1:8000/flights/create" class="btn btn-primary" style="margin-top: 10%">Asignar
                    Vuelos</a>
                <a href="http://127.0.0.1:8000/flights" class="btn btn-primary" style="margin-top: 10%">Ver vuelos
                    asignados</a>
            </div>
        </div>

    </div>

@endsection

resources/views/bases/show.blade.php
@extends('bootstrap.layout')

@section('title', 'Bases Aereas')

@section('content')

    <div style="padding:50px;" class="row">
        <div class="col">
            <label style="color: royalblue">
                <h3>Pilotos</h3>
            </label>
            <table class="table" style=" width:450px">
                <thead class="head-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Horas de Vuelo</th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                @if (count($bases->pilots) > 0)
                    @foreach ($bases->pilots as $pilot)
                        <tr>
                            <th scope="row">{{ $pilot->id }}</th>
                            <td>{{ $pilot->name }}</td>
                            <td>{{ $pilot->flight_time }}</td>
                            <td>{{ $pilot->code }}</td>
                            <td>
                                <a href="http://127.0.0.1:8000/pilots/{{$pilot ->id}}/edit" class="btn btn-primary" style="border: none; background: white;" ><img src="/images/curriculum.png" style="background: white; height: 20px; width: 20px;" title="Editar"></a>
                                <form action="{{route('pilots.destroy', $pilot -> id)}}" method="POST" class="form form-group">
                                    @method('DELETE')
                                    @csrf
                                <button class="btn btn-primary" style="border: none; background: white;" ><img src="/images/borrar.png" style="background: white; height: 20px; width: 20px;" title="Eliminar Piloto" onClick="return confirm('seguro de elinar esta base aerea?')" title="Eliminar"></button>
                                </form>                           
                             </td>
                        </tr>
                    @endforeach
                @else
                @endif

            </table>
        </div>

        <div class="col" style="margin-left: 90px">
            <label style="color: royalblue">
                <h3>Aviones</h3>
            </label>
            <table class="table" style="width: 250px;" >
                <thead class="head-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                @if (count($bases->planes) > 0)
                    @foreach ($bases->planes as $plane)
                        <tr>
                            <th scope="row">{{ $plane->id }}</th>
                            <td>{{ $plane->code }}</td>
                            <td>
                                <a href="http://127.0.0.1:8000/planes/{{$plane ->id}}/edit" class="btn btn-primary" style="border: none; background: white;" ><img src="/images/curriculum.png" style="background: white; height: 20px; width: 20px;" title="Editar"></a>
                                <form action="{{route('planes.destroy', $plane -> id)}}" method="POST" class="form form-group">
                                    @method('DELETE')
                                    @csrf
                                <button class="btn btn-primary" style="border: none; background: white;" ><img src="/images/borrar.png" style="background: white; height: 20px; width: 20px;" title="Eliminar Piloto" onClick="return confirm('seguro de elinar esta base aerea?')" title="Eliminar"></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                @endif

            </table>
        </div>

        <div class="col">
            <label style="color: royalblue">
                <h3>Miembros</h3>
            </label>
            <table class="table" style=" width:350px">
                <thead class="head-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                @if (count($bases->members) > 0)
                    @foreach ($bases->members as $member)
                        <tr>
                            <th scope="row">{{ $member->id }}</th>
                            <td>{{ $member->name }}</td>
                            <td>{{ $member->code }}</td>
                            <td>
                                <a href="http://127.0.0.1:8000/members/{{$member ->id}}/edit" class="btn btn-primary" style="border: none; background: white;" ><img src="/images/curriculum.png" style="background: white; height: 20px; width: 20px;" title="Editar"></a>
                                <form action="{{route('members.destroy', $member -> id)}}" method="POST" class="form form-group">
                                    @method('DELETE')
                                    @csrf
                                <button class="btn btn-primary" style="border: none; background: white;" ><img src="/images/borrar.png" style="background: white; height: 20px; width: 20px;" title="Eliminar Piloto" onClick="return confirm('seguro de elinar esta base aerea?')" title="Eliminar"></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                @endif

            </table>
        </div>
        <div style="margin-left:10%; width:300px;">
            @include('messages.tareas')
        </div>
    </div>

@endsection