routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('bases', basesController::class);

Route::resource('pilots', pilotsController::class);

Route::resource('planes', planesController::class);

Route::resource('members', membersController::class);

Route::resource('flights', flightsController::class);

Route::post('pilots/{basePilotos}', ['as' => 'pilots.store', 'uses' => 'pilotsController@store']);

//Route::put('pilots/{basePilotos}', ['as' => 'pilots.update', 'uses' => 'pilotsController@update']);

Route::post('planes/{basePlanes}', ['as' => 'planes.store', 'uses' => 'planesController@store']);

Route::post('members/{baseMembers}', ['as' => 'members.store', 'uses' => 'membersController@store']);

app/Models/flights.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class flights extends Model
{
    use HasFactory;

    //Hace referencia a la tabla 'flights'
    protected $table = "flights";


    //Relacion uno a muchos(Inversa) entre fligths y pilots.
    public function pilots(){
        return $this->belongsTo('App\Models\pilots');
    }

    //Relacion uno a muchos(Inversa) entre flights y planes.
    public function planes(){
        return $this->belongsTo('App\Models\planes');
    }

    //Relacion muchos a muchos entre flights y members.
    public function members(){
        return $this -> belongsToMany('App\Models\members','members_has_flights','flights_id','members_id');
        }
        
}

app/Http/Controllers/flightsController.php
<?php

namespace App\Http\Controllers;

use App\Models\flights;
use App\Models\members;
use App\Models\pilots;
use App\Models\planes;
use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;

class flightsController extends Controller
{
    /**
     * Retorna la vista donde estan listados todos lo vuelos
     * 
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flights = flights::all();
        return view('flights.index',compact('flights'));
    }

    /**
     * Retorna la vista con el formulario de creacion de vuelos
     * 
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pilots = pilots::all();
        $planes = planes::all();
        $members = members::all();
        $flights = flights::with('pilots','planes','members')->get();
        return view('flights.create',compact('pilots','planes','flights','members'));
    }

    /**
     * Almacena los vuelos en la base de datos
     * 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $flights = new flights();
        $members = $request -> input('members_id');

        $flights -> flight_number = $request -> input('flight_number');
        $flights -> flight_hour = $request -> input('flight_hour');
        $flights -> destiny = $request -> input('destiny');
        $flights -> set_time = $request -> input('set_time');
        $flights -> pilots_id = $request -> input('pilots_id');
        $flights -> planes_id = $request -> input('planes_id');
        
        // dd($members);
        $flights -> save();
        $flights->members()->sync($members);

        


        // foreach($members as $member){
        
        //     $flights -> members() -> sync($member);

        // }

        // $flights -> save();

        // $member -> flights() -> attach($flights);
        
           

        return redirect() -> route('bases.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/flights/create.blade.php
@extends('bootstrap.layout')

@section('title', 'Bases Aereas')

@section('content')

<form class="form-group" method="POST" action="{{route('flights.store')}}" enctype="multipart/form-data">
    @csrf
    <div style="padding: 5%; width:50%; margin-left:25%;">
        <label class="col-form-label col-form-label-lg" style="margin-bottom: 10px;">
            <H1>Asignacion de vuelos</H1>
        </label>
        <div class="row">
            <label class="col-sm-4">Numero del vuelo</label>
            <div class="col">
                <input type="text" name="flight_number" class="form-control">
                <small class="form-text text-muted">Asigne el numero del vuelo</small>
            </div>
        </div>
        <br>
        <div class="row">
            <label class="col-sm-4">Hora de vuelo</label>
            <div class="col">
                <input type="time" name="flight_hour" class="form-control">
                <small class="form-text text-muted">Asigne la hora de vuelo</small>
            </div>
        </div>
        <br>
        <div class="row">
            <label class="col-sm-4">Destino</label>
            <div class="col">
                <input type="text" name="destiny" class="form-control">
                <small class="form-text text-muted">Asigne el destino del vuelo</small>
            </div>
        </div>
        <br>
        <div class="row">
            <label class="col-sm-4">Duracion del vuelo</label>
            <div class="col">
                <input type="text" name="set_time" class="form-control">
                <small class="form-text text-muted">Asigne la duracion del vuelo</small>
            </div>
        </div>
        <br>
        <div class="row">
            <label class="col-sm-4">Piloto que realizara el vuelo</label>
            <div class="col">
                <select class="custom-select col-sm-12" name="pilots_id" style="height: 37px">
                    @foreach ($pilots as $pilot)
                    <option hidden></option>
                    <option value="{{$pilot -> id}}">{{$pilot -> name}}, {{$pilot -> code}}</option>
                    @endforeach
                </select>
                <small class="form-text text-muted">Asigne el piloto</small>
            </div>
        </div>
        <br>
        <div class="row">
            <label class="col-sm-4">Avion que realizara el vuelo</label>
            <div class="col">
                <select class="custom-select col-sm-12" name="planes_id" style="height: 37px">
                    @foreach ($planes as $plane)
                    <option hidden></option>
                    <option value="{{$plane -> id}}">{{$plane -> code}}</option>
                    @endforeach
                </select>
                <small class="form-text text-muted">Asigne el avion</small>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-4">Miembros que estaran en el vuelo</label>
            <div class="col">
                <select multiple class="custom-select col-sm-12" name="members_id[]" >
                    @foreach ($members as $member)
                    <option hidden></option>
                    <option value="{{$member -> id}}">{{$member -> name}}</option>
                    @endforeach
                </select>
                <small class="form-text text-muted">Asigne el avion</small>
            </div>
        </div>

        {{-- <div class="row" hidden>
            <div class="col">
                <input type="text" name="bases_id" class="form-control" value="{{$flights -> id}}">
            </div>
        </div> --}}
        <button type="submit" class="btn btn-primary" style="margin-left: 86%; margin-top:40px">Registrar</button>
    </div>
</form>

@endsection

resources/views/flights/index.blade.php
@extends('bootstrap.layout')

@section('title', 'Vuelo Destinados')

@section('content')

    <div style="padding: 30px; margin-left: 30%">
        <label style="color: royalblue">
            <h1>Lista de los vuelos asignados</h1>
            <hr class="my-4">
        </label>
        <table class="table" style="width: 500px">
            <thead class="head-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Numero de Vuelo</th>
                    <th scope="col">Hora de vuelo</th>
                    <th scope="col">destino</th>
                    <th scope="col">Duracion del vuelo</th>
                    <th scope="col">Piloto</th>
                    <th scope="col">Avion</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($flights as $flight)
                    <tr>
                        <th scope="row">{{ $flight->id }}</th>
                        <td>{{ $flight->flight_number }}</td>
                        <td>{{ $flight->flight_hour }}</td>
                        <td>{{ $flight->destiny }}</td>
                        <td>{{ $flight->set_time }}</td>
                        <td>{{ $flight->pilots_id }}</td>
                        <td>{{ $flight->planes_id }}</td>
                    </tr>
                @endforeach

            </tbody>
        </table>

    @endsection    